# $OpenBSD: Makefile,v 1.11 2014/03/24 08:53:35 jasper Exp $

COMMENT=	more sensible way to change directories

MODULES=	cpan
DISTNAME=	File-chdir-0.1008
REVISION=	0
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
