# $OpenBSD: Makefile,v 1.18 2015/01/21 14:41:38 sthen Exp $

COMMENT=	perl module to the SAX2 NamespaceSupport class

MODULES=	cpan
DISTNAME=	XML-NamespaceSupport-1.11
REVISION=	1
CATEGORIES=	textproc

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
