# $OpenBSD: Makefile,v 1.26 2014/06/20 14:07:50 bluhm Exp $

BROKEN =		needs work on bitrig

SHARED_ONLY =		Yes

COMMENT =		manages IPv4 and IPv6 addresses and subnets

DISTNAME =		NetAddr-IP-4.075
REVISION =		0

CATEGORIES =		net

# perl artistic / GPL
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB +=		c

MODULES =		cpan

.include <bsd.port.mk>
