# $OpenBSD: Makefile,v 1.10 2016/03/20 19:56:09 naddy Exp $

COMMENT=	extensions to Class::DBI for SQLite

MODULES=	cpan
PKG_ARCH=	*
DISTNAME=	Class-DBI-SQLite-0.11
REVISION=	1
CATEGORIES=	databases

# Same as Perl
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	databases/p5-Class-DBI \
		databases/p5-DBD-SQLite

.include <bsd.port.mk>
