# $OpenBSD: Makefile,v 1.13 2015/03/15 09:23:11 ajacoutot Exp $

TRYTOND_MODULE =	timesheet
REVISION =		0

RUN_DEPENDS =		productivity/tryton/company \
			productivity/tryton/company_work_time

.include <bsd.port.mk>
