# $OpenBSD: Makefile,v 1.14 2015/09/09 07:50:21 ajacoutot Exp $

MODPY_EGG_VERSION =	3.2.2

TRYTOND_MODULE =	timesheet
REVISION =		0

RUN_DEPENDS =		productivity/tryton/company \
			productivity/tryton/company_work_time

.include <bsd.port.mk>
