# $OpenBSD: Makefile,v 1.7 2014/04/04 07:45:52 ajacoutot Exp $

PKG_PARCH=		*

COMMENT=		common build utilities for GNOME C++ binding libraries

GNOME_PROJECT=		mm-common
GNOME_VERSION=		0.9.6
REVISION=		0

CATEGORIES=		devel

HOMEPAGE=		http://www.gtkmm.org/

# GPLv2
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		x11/gnome

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
