# $OpenBSD: Makefile,v 1.12 2013/03/11 01:30:26 espie Exp $

COMMENT=	talk to modem devices connected via serial port

DISTNAME=	Device-Modem-1.56
REVISION=	0
CATEGORIES=	comms

MODULES=	cpan

# perl
PERMIT_PACKAGE_CDROM=	Yes

BUILD_DEPENDS=	comms/p5-Device-SerialPort>=1

.include <bsd.port.mk>
