# $OpenBSD: Makefile,v 1.1.1.1 2014/12/22 20:34:09 benoit Exp $

COMMENT =	easily timeout long running operations

DISTNAME =	Time-Out-0.11
CATEGORIES =	devel

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

.include <bsd.port.mk>
