# $OpenBSD: Makefile,v 1.10 2013/10/11 23:49:00 naddy Exp $

COMMENT=        cryptographic signatures for objects

MODULES=	cpan
DISTNAME=	Object-Signature-1.05
REVISION=	3
CATEGORIES=     devel

# perl
PERMIT_PACKAGE_CDROM=   Yes

MAKE_ENV=	AUTOMATED_TESTING=Yes TEST_POD=Yes

.include <bsd.port.mk>
