# $OpenBSD: Makefile,v 1.8 2016/03/20 19:56:40 naddy Exp $

COMMENT=	ordered associative arrays for Perl

MODULES=	cpan
PKG_ARCH=	*
DISTNAME =	Tie-IxHash-1.23
REVISION =	0
CATEGORIES=	devel

# Artistic
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
