# $OpenBSD: Makefile,v 1.9 2013/03/11 10:50:07 espie Exp $

COMMENT =		binary serialization library

DISTNAME =		cereal-0.3.5.2
REVISION =		2
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

.include <bsd.port.mk>
