# $OpenBSD: Makefile,v 1.10 2014/12/14 10:22:24 kili Exp $

COMMENT =		binary serialization library

DISTNAME =		cereal-0.4.1.0
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

.include <bsd.port.mk>
