# $OpenBSD: Makefile,v 1.8 2014/12/29 20:11:12 naddy Exp $

COMMENT=	command-line LiveJournal client
DISTNAME=	clive-0.4.0
REVISION=	1
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=ljclive/}

HOMEPAGE=	http://community.livejournal.com/ljclive/

# BSD 3-clause
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB=		c

CONFIGURE_STYLE=gnu

.include <bsd.port.mk>
