# $OpenBSD: Makefile,v 1.18 2013/11/11 15:42:58 merdely Exp $

COMMENT =	extensible framework for Perl server engines

MODULES =	cpan
DISTNAME =	Net-Server-2.007
REVISION =	0
CATEGORIES =	devel net

HOMEPAGE =	http://seamons.com/projects/

# perl
PERMIT_PACKAGE_CDROM =	Yes

MODCPAN_EXAMPLES =	Yes
TEST_DEPENDS =	devel/p5-IO-Multiplex

.include <bsd.port.mk>
