# $OpenBSD: Makefile,v 1.11 2016/03/20 19:56:41 naddy Exp $

COMMENT=	lightweight, universal exporting/require of variables

MODULES=	cpan
PKG_ARCH=	*
V=		0.05
DISTNAME=	UNIVERSAL-exports-${V}
PKGNAME=	p5-Universal-exports-${V}
REVISION=	2
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	devel/p5-Exporter-Lite

.include <bsd.port.mk>
