# $OpenBSD: Makefile,v 1.6 2014/02/08 19:59:17 espie Exp $

COMMENT =	redirect login screen to https

DISTNAME = 	securelogin-6.x-1.x-dev
PKGNAME =	drupal6-securelogin-1
REVISION =	3

.include <bsd.port.mk>
