# $OpenBSD: Makefile,v 1.20 2016/03/20 19:57:04 naddy Exp $

COMMENT=	interface to the UNIX system logger

DISTNAME=	Unix-Syslog-1.1
REVISION=	5
CATEGORIES=	sysutils

# Artistic
PERMIT_PACKAGE_CDROM=	Yes
WANTLIB=		c perl

MODULES=		cpan
CPAN_AUTHOR=		MHARNISCH

.include <bsd.port.mk>
