# $OpenBSD: Makefile,v 1.19 2015/07/16 23:57:27 ajacoutot Exp $

SHARED_ONLY=	Yes

COMMENT=	interface to the UNIX system logger

DISTNAME=	Unix-Syslog-1.1
REVISION=	4
CATEGORIES=	sysutils

# Artistic
PERMIT_PACKAGE_CDROM=	Yes
WANTLIB=		c 

MODULES=		cpan
CPAN_AUTHOR=		MHARNISCH

.include <bsd.port.mk>
