# $OpenBSD: Makefile,v 1.1.1.1 2013/03/26 23:49:55 nigel Exp $

COMMENT =	determine the locale encoding

DISTNAME =	Encode-Locale-1.03
REVISION =	0
CATEGORIES =	textproc
CPAN_AUTHOR =	GAAS

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =	cpan

.include <bsd.port.mk>
