# $OpenBSD: Makefile,v 1.16 2016/03/20 19:56:32 naddy Exp $

COMMENT =	perl module to generate recursive descent parsers

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Parse-RecDescent-1.967009
REVISION =	0
CATEGORIES =	devel

# Artistic
PERMIT_PACKAGE_CDROM =	Yes

TEST_DEPENDS =	devel/p5-Test-Pod>=1.14 \
		devel/p5-Test-Warn

.include <bsd.port.mk>
