# $OpenBSD: Makefile,v 1.7 2016/03/20 19:57:03 naddy Exp $

COMMENT =		perl extension for wait3 system call

MODULES =		cpan
DISTNAME =		Proc-Wait3-0.04
CATEGORIES =		sysutils
REVISION =		2

# Perl
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB += c perl

.include <bsd.port.mk>
