# $OpenBSD: Makefile,v 1.6 2015/07/16 23:57:27 ajacoutot Exp $

COMMENT =		perl extension for wait3 system call

SHARED_ONLY =		Yes
MODULES =		cpan
DISTNAME =		Proc-Wait3-0.04
CATEGORIES =		sysutils
REVISION =		2

# Perl
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB += c

.include <bsd.port.mk>
