# $OpenBSD: Makefile,v 1.8 2015/09/19 21:52:34 ajacoutot Exp $

TRYTOND_MODULE =	stock_lot
REVISION =		0

RUN_DEPENDS =		productivity/tryton/product \
			productivity/tryton/stock

.include <bsd.port.mk>
