# $OpenBSD: Makefile,v 1.2 2013/01/30 15:28:25 espie Exp $

COMMENT =	nice theme for content heavy sites
DISTNAME=	newsflash-7.x-2.4
PKGNAME =	drupal7-theme-newsflash-2.4
REVISION =	0

# still GPL
HOMEPAGE =	http://www.roopletheme.com/

MODDRUPAL_THEME =	Yes

.include <bsd.port.mk>
