# $OpenBSD: Makefile,v 1.10 2016/03/20 19:57:09 naddy Exp $

COMMENT=	perl extension for parsing ASCIIMathML text into MathML

DISTNAME=	Text-ASCIIMathML-0.81
REVISION=	0
CATEGORIES=	textproc
MODULES=	cpan
PKG_ARCH=	*

CPAN_AUTHOR=	NODINE

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
