# $OpenBSD: Makefile,v 1.7 2013/10/11 23:48:37 naddy Exp $

COMMENT=	xpath matching for object trees

MODULES=	cpan
DISTNAME=	Class-XPath-1.4
REVISION=	1
CATEGORIES=	devel textproc

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
