# $OpenBSD: Makefile,v 1.11 2013/07/05 00:56:41 bluhm Exp $

COMMENT =		perl module to guess file type from contents

DISTNAME =		File-MMagic-1.30
REVISION =		0

CATEGORIES =		misc

# misc, Apache
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

.include <bsd.port.mk>
