# $OpenBSD: Makefile,v 1.15 2013/10/11 23:48:44 naddy Exp $

COMMENT=		per-line Perl profiler

MODULES=		cpan
DISTNAME=		Devel-SmallProf-2.02
REVISION=		1
CATEGORIES=		devel

PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
