# $OpenBSD: Makefile,v 1.10 2015/01/21 14:27:56 sthen Exp $

COMMENT=	inheritable, overridable class data

MODULES=	cpan
DISTNAME=	Class-Data-Inheritable-0.08
REVISION=	1
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
