# $OpenBSD: Makefile,v 1.16 2013/10/11 23:51:59 naddy Exp $

COMMENT=	dynamically change some settings of an xterm

DISTNAME=	xtermset-0.5.2
REVISION=	1
CATEGORIES=	x11

# GPL
PERMIT_PACKAGE_CDROM=   Yes

WANTLIB=		c 

MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=clts/}

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
