# $OpenBSD: Makefile,v 1.11 2014/03/21 15:12:38 jasper Exp $

COMMENT =		minimal try/catch with proper localization of $$@

MODULES =		cpan
DISTNAME =		Try-Tiny-0.19
REVISION =		0
CATEGORIES =		devel

# Perl
PERMIT_PACKAGE_CDROM =	Yes

CPAN_AUTHOR =		DOY

.include <bsd.port.mk>
