# $OpenBSD: Makefile,v 1.4 2013/03/11 11:42:42 espie Exp $

COMMENT=	manages templates and performs variable interpolation

MODULES=	cpan
DISTNAME=	CGI-FastTemplate-1.09
REVISION=	1
CATEGORIES=	textproc www
USE_GROFF =	Yes

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
