# $OpenBSD: Makefile,v 1.7 2016/03/20 19:57:19 naddy Exp $

COMMENT=	just-in-time compiler for HTML::Template

MODULES=	cpan
PKG_ARCH=	*
DISTNAME=	HTML-Template-JIT-0.05
REVISION=	1
CATEGORIES=	www

RUN_DEPENDS=	www/p5-HTML-Template \
		devel/p5-Inline

# GPL/Artistic license
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
