# $OpenBSD: Makefile,v 1.5 2012/09/18 14:06:57 espie Exp $

COMMENT =	zap duplicate content through redirects

DISTNAME = 	globalredirect-6.x-1.5
PKGNAME =	drupal6-globalredirect-1.5
REVISION =	0

.include <bsd.port.mk>
