# $OpenBSD: Makefile,v 1.5 2015/01/23 22:07:10 benoit Exp $

COMMENT=	class and object builder

MODULES=	cpan
DISTNAME =	Class-Gomor-1.03
CATEGORIES=	devel

# Artistic
PERMIT_PACKAGE_CDROM=	Yes

MODCPAN_EXAMPLES=	Yes

.include <bsd.port.mk>
