# $OpenBSD: Makefile,v 1.4 2014/06/14 23:25:00 sthen Exp $

SHARED_ONLY=	Yes

COMMENT=	lexically warn about using the indirect method call syntax

MODULES=	cpan
DISTNAME=	indirect-0.31
REVISION=	2
CATEGORIES=	devel

CPAN_AUTHOR=	VPIT

# Perl
PERMIT_PACKAGE_CDROM=	Yes

TEST_DEPENDS=	devel/p5-Devel-Declare

.include <bsd.port.mk>
