# $OpenBSD: Makefile,v 1.6 2015/01/21 14:41:37 sthen Exp $

COMMENT =	parses a query string suitable for external search engines

MODULES =	cpan
DISTNAME =	Search-QueryParser-0.94
REVISION =	1
CATEGORIES =	textproc

# perl
PERMIT_PACKAGE_CDROM =		Yes

.include <bsd.port.mk>
