# $OpenBSD: Makefile,v 1.4 2013/03/11 10:50:06 espie Exp $

COMMENT =		mmap support for strict ByteStrings

DISTNAME =		bytestring-mmap-0.2.2
REVISION =		2
CATEGORIES =		devel
HOMEPAGE =		http://code.haskell.org/~dons/code/bytestring-mmap/

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

.include <bsd.port.mk>
