# $OpenBSD: Makefile,v 1.11 2016/03/20 19:56:23 naddy Exp $

COMMENT=	module to read a file starting at the end

MODULES=	cpan
PKG_ARCH=	*
DISTNAME=	File-ReadBackwards-1.05
REVISION=	0
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
