# $OpenBSD: Makefile,v 1.11 2014/11/25 22:11:04 kili Exp $

COMMENT =		directory-like tree datatype

DISTNAME =		directory-tree-0.11.0
REVISION =		0
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

.include <bsd.port.mk>
