# $OpenBSD: Makefile,v 1.12 2016/03/20 19:56:25 naddy Exp $

COMMENT=	HASH that stores values without a reference count increase

DISTNAME=	Hash-NoRef-0.03
REVISION=	6
CATEGORIES=	devel
MODULES=	cpan

CPAN_AUTHOR=	GMPASSOS

# Perl
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB += c perl

.include <bsd.port.mk>
