# $OpenBSD: Makefile,v 1.7 2013/03/11 11:35:50 espie Exp $

COMMENT=		parse and manipulate DNS Zone files

MODULES=		cpan
DISTNAME=		DNS-ZoneParse-1.10
REVISION=		0
CATEGORIES=		net
USE_GROFF =		Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
