# $OpenBSD: Makefile,v 1.9 2016/03/20 19:56:50 naddy Exp $

COMMENT=		parse and manipulate DNS Zone files

MODULES=		cpan
PKG_ARCH=		*
DISTNAME=		DNS-ZoneParse-1.10
REVISION=		0
CATEGORIES=		net

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
