# $OpenBSD: Makefile,v 1.5 2013/10/11 23:51:42 naddy Exp $

COMMENT =	pure Perl HTTP client

MODULES =	cpan
DISTNAME =	HTTP-Lite-2.44
CATEGORIES =	www

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
