# $OpenBSD: Makefile,v 1.14 2013/03/11 11:35:46 espie Exp $

DISTNAME=	dnstracer-1.9
REVISION=	0
CATEGORIES=	net

# bsd
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB=		c

COMMENT=	domain name system resolution tracer
HOMEPAGE=	http://www.mavetju.org/unix/dnstracer.php
MASTER_SITES=	http://www.mavetju.org/download/

CONFIGURE_STYLE= gnu
USE_GROFF =	Yes

.include <bsd.port.mk>
