# $OpenBSD: Makefile,v 1.15 2015/01/22 12:52:46 naddy Exp $

DISTNAME=	dnstracer-1.9
REVISION=	0
CATEGORIES=	net

# bsd
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB=		c

COMMENT=	domain name system resolution tracer
HOMEPAGE=	http://www.mavetju.org/unix/dnstracer.php
MASTER_SITES=	http://www.mavetju.org/download/

CONFIGURE_STYLE= gnu

.include <bsd.port.mk>
