# $OpenBSD: Makefile,v 1.7 2012/01/28 11:20:52 espie Exp $

COMMENT =	drop-down css admin menu for drupal

DISTNAME = 	admin_menu-6.x-1.8
PKGNAME =	drupal6-admin-menu-1.8
REVISION =	0

.include <bsd.port.mk>
