# $OpenBSD: Makefile,v 1.7 2013/05/30 10:51:23 sthen Exp $

COMMENT=	full screen FTP client

DISTNAME=	cftp-0.12
REVISION=	1
CATEGORIES=	net

HOMEPAGE=	http://ftp.giga.or.at/pub/nih/cftp/

# GPL
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB=		c termcap

MASTER_SITES=	${HOMEPAGE}

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
