# $OpenBSD: Makefile,v 1.8 2013/04/18 23:44:51 sthen Exp $

COMMENT =		encoding and decoding of base36 strings

MODULES =		cpan
DISTNAME =		Math-Base36-0.12
REVISION =		0
CATEGORIES =		math

# Perl
PERMIT_PACKAGE_CDROM =	Yes

TEST_DEPENDS =		devel/p5-Test-Exception \
			devel/p5-Test-Pod \
			devel/p5-Test-Pod-Coverage

.include <bsd.port.mk>
