# $OpenBSD: Makefile,v 1.2 2013/03/11 11:23:55 espie Exp $

COMMENT =	module handles numbers in base 85

DISTNAME =	Math-Base85-0.2
REVISION =	0
CATEGORIES =	math

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

.include <bsd.port.mk>
