# $OpenBSD: Makefile,v 1.1.1.1 2015/06/02 19:15:21 pea Exp $

COMMENT=		Perl extension for simple generation of unique IDs

MODULES=		cpan
DISTNAME=		Data-Uniqid-0.12
CATEGORIES=		devel

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
