# $OpenBSD: Makefile,v 1.5 2012/01/28 11:20:53 espie Exp $

COMMENT =	run drupal scheduled tasks from apache

DISTNAME = 	poormanscron-6.x-2.2
PKGNAME =	drupal6-poormanscron-2.2
REVISION =	1

.include <bsd.port.mk>
