# $OpenBSD: Makefile,v 1.5 2013/10/26 23:55:35 jeremy Exp $

COMMENT =		ruby library wrapping calls to git CLI

DISTNAME =		git-1.2.5
REVISION =		2
CATEGORIES =		devel

HOMEPAGE =		https://github.com/schacon/ruby-git

# MIT
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ruby

CONFIGURE_STYLE =	ruby gem

.include <bsd.port.mk>
