# $OpenBSD: Makefile,v 1.5 2013/03/11 11:44:46 espie Exp $

COMMENT =	lightweight, dependency free HTML/XML generation

MODULES =	cpan
DISTNAME =	HTML-Tiny-1.05
REVISION =	0
CATEGORIES =	www

# Perl
PERMIT_PACKAGE_CDROM =		Yes

MODCPAN_EXAMPLES =	Yes

.include <bsd.port.mk>
