# $OpenBSD: Makefile,v 1.1.1.2 2004/12/08 06:09:36 msf Exp $

COMMENT=	"perl framework for localization"

DISTNAME=	Locale-Maketext-1.09
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	devel perl5

MAINTAINER=	Mathieu Sauve-Frankel <msf@openbsd.org>

# Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=Locale/}

CONFIGURE_STYLE= perl

PKG_ARCH= *

.include <bsd.port.mk>
