# $OpenBSD: Makefile,v 1.2 2014/02/08 19:37:29 espie Exp $

COMMENT =	fine-grained access control

DISTNAME = 	content_access-7.x-1.2-beta2
PKGNAME =	drupal7-content-access-1.2beta2
REVISION =	0

.include <bsd.port.mk>
