# $OpenBSD: Makefile,v 1.20 2014/06/14 23:24:58 sthen Exp $

COMMENT=	set of objects and strings
SHARED_ONLY=	Yes

MODULES=	cpan
DISTNAME=	Set-Object-1.26
REVISION=	5
CATEGORIES=	devel

# Same as perl
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB += c

.include <bsd.port.mk>
