# $OpenBSD: Makefile,v 1.9 2013/03/11 10:50:07 espie Exp $

COMMENT =		Haskell Object Observation Debugger

DISTNAME =		hood-0.2
REVISION =		7
CATEGORIES =		devel

HOMEPAGE =		http://www.ittc.ku.edu/csdl/fpg/Hood

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

.include <bsd.port.mk>
