# $OpenBSD: Makefile,v 1.11 2015/01/22 18:41:16 naddy Exp $

COMMENT=	user-friendly ncurses-based hexeditor with many features

DISTNAME=	hexcurse-1.55
REVISION=	0
CATEGORIES=	editors

HOMEPAGE=	http://www.jewfish.net/description.php?title=HexCurse

# GPL
PERMIT_PACKAGE_CDROM=	Yes
WANTLIB=		c ncurses

MASTER_SITES=	http://jewfish.net/downloads/

CONFIGURE_STYLE= gnu

.include <bsd.port.mk>
