# $OpenBSD: Makefile,v 1.12 2012/09/18 14:06:57 espie Exp $

COMMENT =	date cck and api for drupal

DISTNAME = 	date-6.x-2.9
PKGNAME =	drupal6-date-2.9
REVISION =	0

RUN_DEPENDS =	www/drupal6/cck

.include <bsd.port.mk>
