# $OpenBSD: Makefile,v 1.18 2014/05/04 09:02:40 benoit Exp $

COMMENT =	generate HTML tables for cgi scripts

MODULES =	cpan
DISTNAME =	HTML-Table-2.08a
REVISION =	0
CATEGORIES =	www devel

# Perl
PERMIT_PACKAGE_CDROM =   Yes

.include <bsd.port.mk>
