# $OpenBSD: Makefile,v 1.20 2016/03/20 19:57:18 naddy Exp $

COMMENT =	generate HTML tables for cgi scripts

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	HTML-Table-2.08a
REVISION =	0
CATEGORIES =	www devel

# Perl
PERMIT_PACKAGE_CDROM =   Yes

.include <bsd.port.mk>
