# $OpenBSD: Makefile,v 1.1.1.1 2015/01/02 14:26:48 florian Exp $

COMMENT =	Variable ties made easier

MODULES =	cpan
DISTNAME =	Tie-Simple-1.03
CPAN_AUTHOR =	HANENKAMP
CATEGORIES =	devel

# perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
