# $OpenBSD: Makefile,v 1.3 2014/01/17 19:46:21 juanfra Exp $

COMMENT =		lossless data compressor

DISTNAME =		lzip-1.15
REVISION =		2

HOMEPAGE =		http://lzip.nongnu.org/lzip.html

# GPLv3+
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB =		c m
WANTLIB +=		c++ c++abi pthread

.include <bsd.port.mk>
