# $OpenBSD: Makefile,v 1.10 2015/01/21 14:27:58 sthen Exp $

COMMENT=	perl support to RFC 3066 language tags

MODULES=	cpan
DISTNAME=	I18N-LangTags-0.35
REVISION=	3
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
