# $OpenBSD: Makefile,v 1.23 2014/04/24 23:49:26 bluhm Exp $

COMMENT =		perl framework for SIP

DISTNAME =		Net-SIP-0.687
REVISION =		0

CATEGORIES =		net telephony

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan
RUN_DEPENDS =		net/p5-Net-DNS>=0.56

.include <bsd.port.mk>
