# $OpenBSD: Makefile,v 1.4 2014/06/14 23:26:03 sthen Exp $

COMMENT =		fast, primitive HTTP request parser

SHARED_ONLY =		Yes
MODULES =		cpan
DISTNAME =		HTTP-Parser-XS-0.13
REVISION =		2
CATEGORIES =		www

# Perl
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB += c

.include <bsd.port.mk>
