# $OpenBSD: Makefile,v 1.5 2015/03/20 22:47:42 naddy Exp $

COMMENT =		fast, primitive HTTP request parser

SHARED_ONLY =		Yes
MODULES =		cpan
DISTNAME =		HTTP-Parser-XS-0.13
REVISION =		2
CATEGORIES =		www

# Perl
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB += c

.include <bsd.port.mk>
