# $OpenBSD: Makefile,v 1.14 2014/06/14 23:24:55 sthen Exp $

COMMENT =	comprehensive set of aliasing operations
SHARED_ONLY =	Yes

MODULES =	cpan
DISTNAME =	Data-Alias-1.18
CATEGORIES =	devel
REVISION =	1

# Perl
PERMIT_PACKAGE_CDROM =		Yes

WANTLIB += c

.include <bsd.port.mk>
