# $OpenBSD: Makefile,v 1.17 2015/07/16 23:57:28 ajacoutot Exp $

SHARED_ONLY=	Yes

COMMENT=	very fast Perl templating library

MODULES=	cpan
DISTNAME=	Text-Tmpl-0.33
REVISION=	3
CATEGORIES=	textproc

# Artistic
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB += c

MODCPAN_EXAMPLES=	Yes

.include <bsd.port.mk>
