# $OpenBSD: Makefile,v 1.14 2013/03/19 10:49:57 benoit Exp $

COMMENT = 	Perl library for manipulating frame stack

MODULES =	cpan
DISTNAME =	Sub-Uplevel-0.24
REVISION =	0
EPOCH =		0
CATEGORIES =	devel

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MAKE_ENV =	AUTHOR_TESTING=Yes \
		TEST_POD=Yes

.include <bsd.port.mk>
