# $OpenBSD: Makefile,v 1.12 2013/10/11 23:48:25 naddy Exp $

COMMENT=	represent a series of changes in annotate form

MODULES=	cpan
DISTNAME=	Algorithm-Annotate-0.10
REVISION=	2
CATEGORIES=	devel

PERMIT_PACKAGE_CDROM=   Yes

RUN_DEPENDS=	devel/p5-Algorithm-Diff>=1.1901
BUILD_DEPENDS=	${RUN_DEPENDS}

.include <bsd.port.mk>
