VERSION =		3.9.0

MAINTAINER =		Christophe Prevotaux <c.prevotaux@rural-networks.com>

PKGSPEC =		regina-rexx->=3.9

MAN1 = 			regina-config.1
MAN1 += 		regina.1
MAN1 += 		rxqueue.1
MAN1 += 		rxstack.1

AUTOCONF_VERSION = 	2.69
AUTOMAKE_VERSION = 	1.15

CONFIGURE_STYLE =	autoconf no-autoheader gnu
CONFIGURE_ARGS = 	--with-prefix=${PREFIX}


.include <bsd.port.mk>
