# $OpenBSD: Makefile,v 1.11 2013/10/11 23:51:20 naddy Exp $

COMMENT=	simple eyecandy ASCII Tables

DISTNAME=	Text-SimpleTable-2.03
REVISION=	1
CATEGORIES=	textproc

# Same as Perl
PERMIT_PACKAGE_CDROM=	Yes

MODULES=	cpan

MAKE_ENV=	TEST_POD=Yes

.include <bsd.port.mk>
