# $OpenBSD: Makefile,v 1.6 2013/10/11 23:51:21 naddy Exp $

COMMENT=	convert tree structured items into ascii tree items

DISTNAME=	Text-Thread-0.2
REVISION=	1

CATEGORIES=	textproc

# Artistic
PERMIT_PACKAGE_CDROM=	Yes

MODULES=	cpan

.include <bsd.port.mk>
