# $OpenBSD: Makefile,v 1.2 2012/05/11 07:47:34 espie Exp $

COMMENT =	generate passwords on account creation

DISTNAME = 	genpass-6.x-1.4
PKGNAME =	drupal6-gen-password-1.4
REVISION =	0

.include <bsd.port.mk>
