# $OpenBSD: Makefile,v 1.18 2013/10/11 23:50:32 naddy Exp $

COMMENT=		network traffic viewer
DISTNAME=		pktstat-1.8.4
REVISION=		4
CATEGORIES=		net

# Public Domain
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB=		c m pcap termlib

MASTER_SITES=		http://openbsd.fi/dist/

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
