# $OpenBSD: Makefile,v 1.11 2014/03/23 13:57:46 jasper Exp $

COMMENT=	interface for providing metadata about installed packages

MODULES=	cpan
DISTNAME=	App-Info-0.57
REVISION=	0
CATEGORIES=	devel
USE_GROFF =	Yes

PERMIT_PACKAGE_CDROM=   Yes

CONFIGURE_STYLE=modbuild

.include <bsd.port.mk>
