# $OpenBSD: Makefile,v 1.2 2016/03/20 19:57:07 naddy Exp $

COMMENT =	perldoc that works for modules you don't have installed
DISTNAME =	Pod-Cpandoc-0.15
CATEGORIES =	textproc

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =	cpan
PKG_ARCH =	*

.include <bsd.port.mk>
