# $OpenBSD: Makefile,v 1.13 2014/03/24 08:00:37 jasper Exp $

COMMENT=        pretty printing of data structures

MODULES=	cpan
DISTNAME=	Data-Dump-1.22
REVISION=	0
CATEGORIES=     devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=   Yes

.include <bsd.port.mk>
