# $OpenBSD: Makefile,v 1.12 2014/11/06 17:13:39 sthen Exp $

COMMENT =		PHP support for LZF de/compression

DISTNAME =		LZF-1.6.2
CATEGORIES =		archivers
REVISION =		2

# PHP
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/php/pecl
CONFIGURE_STYLE =	gnu

.include <bsd.port.mk>
