# $OpenBSD: Makefile,v 1.10 2014/06/18 11:18:32 sthen Exp $

COMMENT=	RFC 2822 address parsing and creation

MODULES=	cpan
DISTNAME=	Email-Address-1.905
REVISION=	0
CATEGORIES=	mail

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
