# $OpenBSD: Makefile,v 1.7 2014/02/08 19:48:22 espie Exp $

COMMENT =	publish/unpublish nodes on schedule

DISTNAME = 	scheduler-6.x-1.9
PKGNAME =	drupal6-scheduler-1.9
REVISION =	0

.include <bsd.port.mk>
