# $OpenBSD: Makefile,v 1.1.1.1 2013/08/10 16:07:50 landry Exp $

COMMENT =	advanced PostgreSQL log analyzer

V =		7.1
DISTNAME =	v${V}
PKGNAME =	pgbadger-${V}
CATEGORIES =	databases

HOMEPAGE =	http://dalibo.github.io/pgbadger/

# GPLv2
PERMIT_PACKAGE_CDROM =	Yes

GH_ACCOUNT =	dalibo
GH_PROJECT =	pgbadger
GH_TAGNAME =	v${V}

CONFIGURE_STYLE =	perl

.include <bsd.port.mk>
