# $OpenBSD: Makefile,v 1.4 2016/03/20 19:56:26 naddy Exp $

COMMENT =	essential utilities for the Iterator class.

DISTNAME =	Iterator-Util-0.02
REVISION =	0
CATEGORIES =	devel

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan
PKG_ARCH =		*

RUN_DEPENDS =		devel/p5-Iterator

.include <bsd.port.mk>
