# $OpenBSD: Makefile,v 1.6 2013/10/11 23:49:21 naddy Exp $

COMMENT=		track the number of times subs are called

MODULES=		cpan
DISTNAME=		Test-SubCalls-1.09
REVISION=		1
CATEGORIES=		devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

TEST_DEPENDS=	devel/p5-Hook-LexWrap

.include <bsd.port.mk>
