# $OpenBSD: Makefile,v 1.8 2015/01/21 14:42:33 sthen Exp $

COMMENT =	FastMmap cache store for Catalyst (deprecated)

MODULES =	cpan
DISTNAME =	Catalyst-Plugin-Cache-Store-FastMmap-0.02
REVISION =	2
CATEGORIES =	www

# Perl/MIT
PERMIT_PACKAGE_CDROM =		Yes

RUN_DEPENDS =	devel/p5-Cache-FastMmap \
		devel/p5-Path-Class \
		www/p5-Catalyst-Plugin-Cache

.include <bsd.port.mk>
