# $OpenBSD: Makefile,v 1.11 2016/03/20 19:56:07 naddy Exp $

COMMENT=	module to read TNEF files

DISTNAME =	Convert-TNEF-0.18
REVISION =	0
CATEGORIES=	converters
MODULES=	cpan
PKG_ARCH=	*

# Artistic
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	mail/p5-MIME-tools

.include <bsd.port.mk>
