# $OpenBSD: Makefile,v 1.10 2013/03/25 09:04:06 benoit Exp $

COMMENT=	module to read TNEF files

DISTNAME =	Convert-TNEF-0.18
REVISION =	0
CATEGORIES=	converters
MODULES=	cpan

# Artistic
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	mail/p5-MIME-tools

.include <bsd.port.mk>
