# $OpenBSD: Makefile,v 1.7 2013/10/11 23:51:30 naddy Exp $

COMMENT=	process and decode WWW forms and cookies

DISTNAME=	CGI-Lite-2.02
REVISION=	1
CATEGORIES=	www

# Perl
PERMIT_PACKAGE_CDROM=	Yes

MODULES=	cpan

MODCPAN_EXAMPLES=	Yes

.include <bsd.port.mk>
