# $OpenBSD: Makefile,v 1.7 2014/06/14 23:25:41 sthen Exp $

SHARED_ONLY =		Yes

COMMENT =		perl interface to OpenBSD socket splicing

DISTNAME =		BSD-Socket-Splice-0.05
REVISION =		1

CATEGORIES =		net

# perl
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB +=		c

MODULES =		cpan

.include <bsd.port.mk>
