# $OpenBSD: Makefile,v 1.6 2013/03/11 10:50:07 espie Exp $

COMMENT=		simple type class for success/failure computations

DISTNAME=		failure-0.1.0.1
REVISION=		4
CATEGORIES=		devel

HOMEPAGE=		http://www.haskell.org/haskellwiki/Failure

# 3-clause BSD
PERMIT_PACKAGE_CDROM =	Yes

MODULES=		lang/ghc

MODGHC_BUILD =          cabal hackage haddock register

.include <bsd.port.mk>
