# $OpenBSD: Makefile,v 1.17 2015/01/21 14:27:59 sthen Exp $

COMMENT=	module for containing a set of scalars

MODULES=	cpan

DISTNAME =	Set-Scalar-1.29
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=   Yes

.include <bsd.port.mk>
