# $OpenBSD: Makefile,v 1.6 2013/06/12 13:35:11 sthen Exp $

COMMENT =	holiday classes for PHP
DISTNAME =	Date_Holidays-0.21.8
REVISION =	0

# BSD

RUN_DEPENDS =	devel/pear-Date \
		textproc/pear-XML-Serializer

.include <bsd.port.mk>
