# $OpenBSD: Makefile,v 1.6 2016/03/20 19:57:03 naddy Exp $

COMMENT =	Perl interface for the system 'at' command

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Schedule-At-1.15
REVISION =	0
CATEGORIES =	sysutils

# Perl
PERMIT_PACKAGE_CDROM =  Yes

.include <bsd.port.mk>
