# $OpenBSD: Makefile,v 1.3 2016/03/20 19:56:58 naddy Exp $

COMMENT =	pure Perl implementation for an XML-RPC client and server

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	XML-RPC-0.9
REVISION =	0
CATEGORIES =	net devel

# Perl
PERMIT_PACKAGE_CDROM =	Yes

RUN_DEPENDS =		textproc/p5-XML-TreePP

CPAN_AUTHOR =		DAAN
CONFIGURE_STYLE =	perl

.include <bsd.port.mk>
