# $OpenBSD: Makefile,v 1.9 2013/10/11 23:51:00 naddy Exp $

COMMENT=	limits the number of forked concurrent processes

DISTNAME=	Proc-Queue-1.23
REVISION=	1
CATEGORIES=	sysutils
MODULES=	cpan

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
