# $OpenBSD: Makefile,v 1.10 2016/03/20 19:57:03 naddy Exp $

COMMENT=	limits the number of forked concurrent processes

DISTNAME=	Proc-Queue-1.23
REVISION=	1
CATEGORIES=	sysutils
MODULES=	cpan
PKG_ARCH=	*

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
