# $OpenBSD: Makefile,v 1.9 2013/05/13 07:49:43 benoit Exp $

COMMENT =		compare two directories using callbacks

MODULES =		cpan
DISTNAME =		File-DirCompare-0.7
REVISION =		0
CATEGORIES =		devel

CPAN_AUTHOR =		GAVINC

# Perl
PERMIT_PACKAGE_CDROM =	Yes

CONFIGURE_STYLE =	perl

.include <bsd.port.mk>
