# $OpenBSD: Makefile,v 1.3 2014/06/14 23:24:56 sthen Exp $

COMMENT =	walk all of perl memory arena

SHARED_ONLY =	Yes
MODULES =	cpan
DISTNAME =	Devel-Gladiator-0.04
CATEGORIES =	devel
REVISION =	1

TEST_DEPENDS =	devel/p5-PadWalker
# perl
PERMIT_PACKAGE_CDROM =   Yes

.include <bsd.port.mk>
