# $OpenBSD: Makefile,v 1.21 2014/06/28 21:08:09 kili Exp $

COMMENT=	multi-platform file synchronization tool

V=		2.40.102
REVISION =	3

MASTER_SITES=	${HOMEPAGE}download/releases/stable/

.include <bsd.port.mk>
