# $OpenBSD: Makefile,v 1.4 2015/09/29 10:52:11 sthen Exp $

COMMENT=		refactoring library

REVISION=		1
MODPY_EGG_VERSION=	0.9.4
DISTNAME=		rope-${MODPY_EGG_VERSION}
CATEGORIES=     	devel
REVISION=		0

# GPL
PERMIT_PACKAGE_CDROM=	Yes

HOMEPAGE=		http://rope.sf.net/

MODPY_PI =		Yes

MODPY_SETUPTOOLS=	Yes

MODULES=		lang/python

SUBST_VARS=		DISTNAME

.include <bsd.port.mk>
