# $OpenBSD: Makefile,v 1.1.1.1 2013/05/31 21:39:42 jasper Exp $

COMMENT=		refactoring library

DISTNAME=		rope-0.9.4
REVISION=		0
CATEGORIES=     	devel

# GPL
PERMIT_PACKAGE_CDROM=	Yes

HOMEPAGE=		http://rope.sf.net/

MASTER_SITES=		${MASTER_SITE_PYPI:=/r/rope/}

MODPY_SETUPTOOLS=	Yes

MODULES=		lang/python

SUBST_VARS=		DISTNAME

.include <bsd.port.mk>
