# $OpenBSD: Makefile,v 1.32 2011/05/23 13:42:10 gsoares Exp $

COMMENT=	 BSD licensed implementations of essential compilation tools and libraries for handling ELF based program images.

PKGNAME=	bitrig-elftoolchain-0.5.1
DISTNAME=	elftoolchain-0.5.1
EXTRACT_SUFX=	.tgz
CATEGORIES=	bitrig
#REVISION =	0

HOMEPAGE=	http://sourceforge.net/apps/trac/elftoolchain/
MAINTAINER =	Marco Peereboom <marco@bitrig.org>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=elftoolchain/}

.include <bsd.port.mk>
