# $OpenBSD: Makefile,v 1.5 2014/12/27 09:05:06 benoit Exp $

COMMENT =		less indentation and newlines plus sub deparsing

DISTNAME =		Data-Dumper-Concise-2.022
CATEGORIES =		devel

# perl_5
PERMIT_PACKAGE_CDROM =	Yes

MODULES =	cpan

.include <bsd.port.mk>
