# $OpenBSD: Makefile,v 1.3 2014/03/10 01:18:48 afresh1 Exp $

COMMENT =		less indentation and newlines plus sub deparsing

DISTNAME =		Data-Dumper-Concise-2.021
REVISION =		0
CATEGORIES =		devel

# perl_5
PERMIT_PACKAGE_CDROM =	Yes

MODULES =	cpan

.include <bsd.port.mk>
