# $OpenBSD: Makefile,v 1.12 2015/03/15 21:38:24 benoit Exp $

COMMENT =	lightweight exception class

MODULES =	cpan
DISTNAME =	Class-Throwable-0.13
CATEGORIES =	devel

# perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
