# $OpenBSD: Makefile,v 1.8 2013/10/11 23:48:51 naddy Exp $

COMMENT=	filehandle which supports ungetting of multiple bytes

MODULES=	cpan
DISTNAME=	FileHandle-Unget-0.1623
REVISION=	1
CATEGORIES=	devel

# GPLv2
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
