# $OpenBSD: Makefile,v 1.6 2013/10/11 23:49:10 naddy Exp $

COMMENT=        lexically scoped resource management

MODULES=	cpan
DISTNAME=	Scope-Guard-0.20
REVISION=	1
CATEGORIES=     devel

CPAN_AUTHOR=	CHOCOLATE

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
