# $OpenBSD: Makefile,v 1.5 2014/04/14 14:02:43 benoit Exp $

COMMENT =	share Perl variables between processes

MODULES =	cpan
DISTNAME =	IPC-Shareable-0.61
REVISION =	0
CATEGORIES =	devel

# GPLv2
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
