# $OpenBSD: Makefile,v 1.7 2013/03/11 10:50:20 espie Exp $

COMMENT=	parser for plain-text configuration files

MODULES=	cpan
DISTNAME=	Parse-PlainConfig-2.06
REVISION=	1
CATEGORIES=	devel
USE_GROFF =	Yes

# GPL
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	devel/p5-Paranoid

.include <bsd.port.mk>
