# $OpenBSD: Makefile,v 1.14 2015/04/02 14:21:18 jasper Exp $

COMMENT =		random assortment of WSGI servers, middleware

MODPY_EGG_VERSION =	1.0.2
DISTNAME =		flup-${MODPY_EGG_VERSION}
PKGNAME =		py-flup-${MODPY_EGG_VERSION}
REVISION =		4

CATEGORIES =		www

HOMEPAGE =		http://trac.saddi.com/flup

# BSD
PERMIT_PACKAGE_CDROM =	Yes

MODPY_PI =		Yes

MODULES =		lang/python

NO_TEST =		Yes

MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
