# $OpenBSD: Makefile,v 1.13 2015/03/15 09:23:11 ajacoutot Exp $

TRYTOND_MODULE =	stock_product_location
REVISION =		0

RUN_DEPENDS =		productivity/tryton/product \
			productivity/tryton/stock

.include <bsd.port.mk>
