# $OpenBSD: Makefile,v 1.10 2014/05/11 16:27:43 afresh1 Exp $

COMMENT =	expose the flag which marks global destruction

DISTNAME =	Devel-GlobalDestruction-0.12
REVISION =	0
CATEGORIES =	devel

# perl_5
PERMIT_PACKAGE_CDROM =	Yes

MODULES =	cpan

RUN_DEPENDS =	devel/p5-Sub-Exporter-Progressive>=0.001011

.include <bsd.port.mk>
