# $OpenBSD: Makefile,v 1.13 2013/10/11 23:50:02 naddy Exp $

COMMENT=	module to internal operations of neural networks

MODULES=	cpan
DISTNAME=	AI-Perceptron-1.0
REVISION=	1
CATEGORIES=	math

# Perl
PERMIT_PACKAGE_CDROM=	Yes

CONFIGURE_STYLE=	modbuild

RUN_DEPENDS=		devel/p5-accessors

.include <bsd.port.mk>
