# $OpenBSD: Makefile,v 1.17 2014/07/25 09:17:16 zhuk Exp $

COMMENT =	Run Perl standard test scripts with statistics

DISTNAME =	Test-Harness-3.30
REVISION =	0
CATEGORIES =	devel
REVISION =	0

# perl_5
PERMIT_PACKAGE_CDROM =	Yes

MODULES =	cpan

.include <bsd.port.mk>
