# $OpenBSD: Makefile,v 1.3 2014/02/08 19:17:20 espie Exp $

COMMENT =	conditionally executed actions based on occurring events

DISTNAME = 	rules-7.x-2.6
PKGNAME =	drupal7-rules-2.6
REVISION =	0
RUN_DEPENDS =	www/drupal7/entity

.include <bsd.port.mk>
