# $OpenBSD: Makefile,v 1.2 2013/03/11 11:41:32 espie Exp $

COMMENT =		SUPress command stdout / stderr UNless ERror

DISTNAME =		supuner-0.1
REVISION =		0
CATEGORIES =		sysutils

HOMEPAGE =		http://tratt.net/laurie/src/supuner/

# BSD / MIT
PERMIT_PACKAGE_CDROM =	Yes

MASTER_SITES =		${HOMEPAGE}releases/

NO_TEST =		Yes
NO_BUILD =		Yes

.include <bsd.port.mk>
