# $OpenBSD: Makefile,v 1.7 2012/08/23 09:45:11 espie Exp $

COMMENT =	conditionally executed actions based on occurring events

DISTNAME = 	rules-6.x-1.5
PKGNAME =	drupal6-rules-1.5
REVISION =	0

.include <bsd.port.mk>
