# $OpenBSD: Makefile,v 1.4 2014/02/08 19:17:20 espie Exp $

COMMENT =	drupal views, smart content lists

DISTNAME = 	views-7.x-3.7
PKGNAME =	drupal7-views-3.7
REVISION =	0

RUN_DEPENDS =	www/drupal7/ctools

.include <bsd.port.mk>
