# $OpenBSD: Makefile,v 1.9 2016/03/20 19:57:19 naddy Exp $

COMMENT=	use HTML Templates from CGI scripts

MODULES=	cpan
PKG_ARCH=	*
DISTNAME=	HTML-Template-2.9
REVISION=	0
CATEGORIES=	www

HOMEPAGE=	http://sourceforge.net/projects/html-template/

# GPL/Artistic license
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
