# $OpenBSD: Makefile,v 1.8 2013/10/11 23:51:40 naddy Exp $

COMMENT=	use HTML Templates from CGI scripts

MODULES=	cpan
DISTNAME=	HTML-Template-2.9
REVISION=	0
CATEGORIES=	www

HOMEPAGE=	http://sourceforge.net/projects/html-template/

# GPL/Artistic license
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
