# $OpenBSD: Makefile,v 1.12 2013/10/11 23:48:28 naddy Exp $

COMMENT=	backend to diagram op trees

MODULES=	cpan
DISTNAME=	B-Graph-0.51
REVISION=	2
CATEGORIES=	devel

PERMIT_PACKAGE_CDROM=   Yes

.include <bsd.port.mk>
