# $OpenBSD: Makefile,v 1.14 2013/10/11 23:48:47 naddy Exp $

COMMENT=	recursive copy of files and directories

MODULES=	cpan
DISTNAME=	File-Copy-Recursive-0.38
REVISION=	1
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
