# $OpenBSD: Makefile,v 1.1.1.1 2014/10/31 12:01:58 landry Exp $

COMMENT =	Pythonic argument parser

MODPY_EGG_VERSION = 0.6.2
DISTNAME =	docopt-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}
CATEGORIES =	devel

HOMEPAGE =	http://docopt.org

# MIT
PERMIT_PACKAGE_CDROM =  Yes

MASTER_SITES =	${MASTER_SITE_PYPI:=d/docopt/}

MODULES =	lang/python
MODPY_SETUPTOOLS = Yes

.include <bsd.port.mk>
