# $OpenBSD: Makefile,v 1.14 2015/09/19 21:33:37 ajacoutot Exp $

MODPY_EGG_VERSION =	3.2.2

TRYTOND_MODULE =	account_invoice_line_standalone
REVISION =		0

RUN_DEPENDS =		productivity/tryton/account_invoice

.include <bsd.port.mk>
