# $OpenBSD: Makefile,v 1.13 2015/03/15 09:23:10 ajacoutot Exp $

TRYTOND_MODULE =	account_invoice_line_standalone
REVISION =		0

RUN_DEPENDS =		productivity/tryton/account_invoice

.include <bsd.port.mk>
