# $OpenBSD: Makefile,v 1.2 2014/11/06 16:47:35 benoit Exp $

COMMENT =	minimalist role composition tool

MODULES =	cpan
DISTNAME =	Role-Tiny-1.003004
CATEGORIES =	devel

CPAN_AUTHOR =	HAARG

# Perl
PERMIT_PACKAGE_CDROM =	Yes

TEST_DEPENDS =	devel/p5-Test-Fatal

.include <bsd.port.mk>
