# $OpenBSD: Makefile,v 1.8 2016/03/20 19:56:24 naddy Exp $

COMMENT=	simple wrapper around Getopt::Long

DISTNAME =	Getopt-Simple-1.52
REVISION =	0
CATEGORIES=     devel

EXTRACT_SUFX=	.tgz

# Artistic
PERMIT_PACKAGE_CDROM=   Yes

MODULES=	cpan
PKG_ARCH=	*

MAKE_ENV+=		TEST_POD=1

.include <bsd.port.mk>
