# $OpenBSD: Makefile,v 1.2 2013/03/11 11:42:44 espie Exp $

COMMENT=	camelcase, de-camelcase

MODULES=	cpan
DISTNAME=	String-CamelCase-0.02
REVISION=	0
CATEGORIES=	textproc

# Same as Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
