# $OpenBSD: Makefile,v 1.28 2013/03/11 11:44:47 espie Exp $

COMMENT=	library to parse Uniform Resource Identifiers

MODULES=	cpan
DISTNAME=	URI-1.60
REVISION=	0
CATEGORIES=	www

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
