# $OpenBSD: Makefile,v 1.13 2015/07/09 14:02:08 espie Exp $

COMMENT =	test site as another user
CATEGORIES =	devel

DISTNAME =	masquerade-6.x-1.9
PKGNAME =	drupal6-masquerade-1.9

.include <bsd.port.mk>
