# $OpenBSD: Makefile,v 1.12 2012/01/28 11:20:53 espie Exp $

COMMENT =	test site as another user
CATEGORIES =	devel

DISTNAME =	masquerade-6.x-1.7
PKGNAME =	drupal6-masquerade-1.7
REVISION =	0

.include <bsd.port.mk>
