# $OpenBSD: Makefile,v 1.3 2014/04/29 08:05:32 ajacoutot Exp $

TRYTOND_MODULE =	bank
REVISION =		0

RUN_DEPENDS =		productivity/tryton/currency \
			productivity/tryton/party

.include <bsd.port.mk>
