# $OpenBSD: Makefile,v 1.19 2014/07/12 23:51:29 jasper Exp $

COMMENT=	Scalable Vector Graphics (SVG) in perl

DISTNAME=	SVG-2.59
REVISION=	0
CATEGORIES=	graphics devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

MODULES=	cpan
USE_GROFF =	Yes

.include <bsd.port.mk>
