# $OpenBSD: Makefile,v 1.10 2013/03/11 11:44:44 espie Exp $

COMMENT = 		MVC web framework for perl

MODULES =		cpan
DISTNAME =		CGI-Application-4.50
REVISION =		0
CATEGORIES =		www
HOMEPAGE =		http://www.cgi-app.org/
USE_GROFF =		Yes

# perl
PERMIT_PACKAGE_CDROM =	Yes

CONFIGURE_STYLE =	modbuild
RUN_DEPENDS =		www/p5-HTML-Template

.include <bsd.port.mk>
