# $OpenBSD: Makefile,v 1.9 2014/06/14 23:24:59 sthen Exp $

SHARED_ONLY=	Yes

COMMENT=	ordered hashes for Perl

DISTNAME=	Tie-Hash-Indexed-0.05
REVISION=	5
CATEGORIES=	devel
MODULES=	cpan
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB += c

.include <bsd.port.mk>
