# $OpenBSD: Makefile,v 1.2 2013/03/11 10:50:17 espie Exp $

COMMENT =	update access and modification timestamps of files

MODULES =	cpan
DISTNAME =	File-Touch-0.08
REVISION =	0
CATEGORIES =	devel

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
