# $OpenBSD: Makefile,v 1.3 2014/11/11 07:05:38 benoit Exp $

COMMENT =	update access and modification timestamps of files

MODULES =	cpan
DISTNAME =	File-Touch-0.09
CATEGORIES =	devel

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
