# $OpenBSD: Makefile,v 1.10 2015/03/15 08:52:14 ajacoutot Exp $

MODPY_EGG_VERSION =	3.2.1

TRYTOND_MODULE =	product_cost_history
REVISION =		0

RUN_DEPENDS =		productivity/tryton/product

.include <bsd.port.mk>
