# $OpenBSD: Makefile,v 1.12 2015/09/16 06:20:04 ajacoutot Exp $

MODPY_EGG_VERSION =	3.2.2

TRYTOND_MODULE =	product_cost_history
REVISION =		0

RUN_DEPENDS =		productivity/tryton/product

.include <bsd.port.mk>
