# $OpenBSD: Makefile,v 1.7 2014/04/13 01:01:38 naddy Exp $

COMMENT=        generate Perl class hierarchies

MODULES=	cpan
DISTNAME=	Class-Generate-1.14
REVISION=	0
CATEGORIES=     devel

# Perl
PERMIT_PACKAGE_CDROM=	Yes

CONFIGURE_STYLE=	modbuild

.include <bsd.port.mk>
