# $OpenBSD: Makefile,v 1.15 2015/09/19 21:52:33 ajacoutot Exp $

TRYTOND_MODULE =	account_product
REVISION =		0

RUN_DEPENDS =		productivity/tryton/account \
			productivity/tryton/company \
			productivity/tryton/product

.include <bsd.port.mk>
