# $OpenBSD: Makefile,v 1.8 2013/03/11 02:52:06 espie Exp $

COMMENT=	more complex retrieve_all() for Class::DBI

MODULES=	cpan
DISTNAME=	Class-DBI-Plugin-RetrieveAll-1.04
REVISION=	1
CATEGORIES=	databases
USE_GROFF =	Yes

# Same as Perl
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	databases/p5-Class-DBI
TEST_DEPENDS=	databases/p5-DBD-SQLite

.include <bsd.port.mk>
