# $OpenBSD: Makefile,v 1.12 2015/09/19 21:52:34 ajacoutot Exp $

TRYTOND_MODULE =	purchase_invoice_line_standalone
REVISION =		0

RUN_DEPENDS =		productivity/tryton/account_invoice_line_standalone \
			productivity/tryton/purchase

.include <bsd.port.mk>
