# $OpenBSD: Makefile,v 1.4 2012/01/28 11:20:53 espie Exp $

COMMENT =	database introspection

CATEGORIES += 	devel
DISTNAME = 	schema-6.x-1.7
PKGNAME =	drupal6-schema-1.7
REVISION =	1

.include <bsd.port.mk>
