# $OpenBSD: Makefile,v 1.10 2014/04/01 17:12:01 sthen Exp $

COMMENT=	compare numbers

MODULES=	cpan
DISTNAME=	Number-Compare-0.03
REVISION=	0
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
