# $OpenBSD: Makefile,v 1.3 2014/02/08 19:59:17 espie Exp $

COMMENT =	redirect login screen to https

DISTNAME = 	securelogin-7.x-1.4
PKGNAME =	drupal7-securelogin-1.4
REVISION =	0

.include <bsd.port.mk>
