# $OpenBSD: Makefile,v 1.5 2013/03/11 11:35:52 espie Exp $

COMMENT=		FTP client class with automatic reconnect on failure

MODULES=		cpan
DISTNAME=		Net-FTP-AutoReconnect-0.2
REVISION=		1
CATEGORIES=		net
USE_GROFF =		Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
