# $OpenBSD: Makefile,v 1.1.1.1 2012/04/10 12:49:31 espie Exp $

COMMENT =	automatic node titles for drupal

DISTNAME = 	auto_nodetitle-7.x-1.0
PKGNAME =	drupal7-automatic-nodetitle-1.0
REVISION =	0

.include <bsd.port.mk>
