# $OpenBSD: Makefile,v 1.13 2015/01/30 13:34:40 jasper Exp $

COMMENT=		extracts files from Microsoft CAB archives

DISTNAME=		cabextract-1.4
REVISION=		0
CATEGORIES=		archivers

HOMEPAGE=		http://www.cabextract.org.uk/

# GPLv2
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB=		c

MASTER_SITES=		${HOMEPAGE}

CONFIGURE_STYLE=	gnu
SEPARATE_BUILD=		Yes

.include <bsd.port.mk>
