# $OpenBSD: Makefile,v 1.10 2016/03/20 19:56:19 naddy Exp $

COMMENT=	is a particular year a leap year

MODULES=	cpan
PKG_ARCH=	*
DISTNAME=	Date-Leapyear-1.72
REVISION=	1
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
