# $OpenBSD: Makefile,v 1.13 2013/10/11 23:51:15 naddy Exp $

COMMENT=		Quote strings for passing through the shell

MODULES=		cpan
DISTNAME=		String-ShellQuote-1.04
REVISION=		1
CATEGORIES=		textproc

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
