# $OpenBSD: Makefile,v 1.14 2016/03/20 19:57:08 naddy Exp $

COMMENT=		Quote strings for passing through the shell

MODULES=		cpan
PKG_ARCH=		*
DISTNAME=		String-ShellQuote-1.04
REVISION=		1
CATEGORIES=		textproc

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
