# $OpenBSD: Makefile,v 1.8 2013/01/18 11:17:35 sthen Exp $

COMMENT =	set up meta keywords for any node

DISTNAME =	nodewords-6.x-1.14
PKGNAME =	drupal6-meta-tags-1.14
REVISION =	0

.include <bsd.port.mk>
