# $OpenBSD: Makefile,v 1.15 2013/03/11 11:41:29 espie Exp $

COMMENT=		SSH monitoring

DISTNAME=		autossh-1.4c
REVISION=		0
CATEGORIES=		sysutils

MASTER_SITES=		${HOMEPAGE}

HOMEPAGE=		http://www.harding.motd.ca/autossh/

# BSD
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB=		c

EXTRACT_SUFX=		.tgz

USE_GROFF=		Yes
NO_TEST=		Yes

CONFIGURE_STYLE=	gnu dest

.include <bsd.port.mk>
