# $OpenBSD: Makefile,v 1.6 2013/03/11 11:42:45 espie Exp $

COMMENT=	re-usable XPath engine for DOM-like trees

MODULES=	cpan
DISTNAME=	XML-XPathEngine-0.12
REVISION=	1
CATEGORIES=	textproc
USE_GROFF =	Yes

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
