# $OpenBSD: Makefile,v 1.12 2014/03/16 21:54:40 afresh1 Exp $

COMMENT =	convert singular to plural, select a or an

MODULES =	cpan
DISTNAME =	Lingua-EN-Inflect-1.895
REVISION =	0
CATEGORIES =	textproc

# Same as Perl
# unknown
PERMIT_PACKAGE_CDROM =	Yes

MODCPAN_EXAMPLES =	Yes
MODCPAN_EXAMPLES_DIST =	demo

.include <bsd.port.mk>
