# $OpenBSD: Makefile,v 1.8 2013/03/11 10:50:06 espie Exp $

COMMENT =		priority search queue

DISTNAME =		PSQueue-1.1
REVISION =		6
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

.include <bsd.port.mk>
