# $OpenBSD: Makefile,v 1.11 2015/12/20 11:24:12 kili Exp $

COMMENT =		priority search queue

DISTNAME =		PSQueue-1.1
REVISION =		8
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	B2W2Jqwxlgm7tpuk3TcoPN

.include <bsd.port.mk>
