# $OpenBSD: Makefile,v 1.8 2013/03/11 11:42:41 espie Exp $

COMMENT =		simple XML library

DISTNAME =		xml-1.3.7
REVISION =		6
CATEGORIES =		textproc

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

.include <bsd.port.mk>
