# $OpenBSD: Makefile,v 1.2 2013/03/11 10:50:19 espie Exp $

COMMENT=	expiry plug-in for Memoize that adds LRU cache expiration

DISTNAME=	Memoize-ExpireLRU-0.55
REVISION=	0
CATEGORIES=	devel

# Same as Perl
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		cpan

.include <bsd.port.mk>
