# $OpenBSD: Makefile,v 1.8 2015/09/20 21:16:14 kili Exp $

BROKEN =		needs an update, not used by anything useful

COMMENT =		singleton tuple

DISTNAME =		OneTuple-0.2.1
REVISION =		2
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	Ax3IscSqFKqJoTs5Z2AElr

.include <bsd.port.mk>
