# $OpenBSD: Makefile,v 1.17 2014/06/14 23:25:42 sthen Exp $

SHARED_ONLY =		Yes

COMMENT =		Perl defines relating to AF_INET6 sockets

DISTNAME =		Socket6-0.25
REVISION =		1

CATEGORIES =		net devel

# 3-clause BSD
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB +=		c

MODULES =		cpan

.include <bsd.port.mk>
