# $OpenBSD: Makefile,v 1.1.1.1 2012/04/10 12:50:24 espie Exp $

COMMENT =	generate passwords on account creation

DISTNAME = 	genpass-7.x-1.0
PKGNAME =	drupal7-gen-password-1.0
REVISION =	0

.include <bsd.port.mk>
