# $OpenBSD: Makefile,v 1.10 2015/09/19 21:52:33 ajacoutot Exp $

TRYTOND_MODULE =	carrier
REVISION =		0

RUN_DEPENDS =		productivity/tryton/party \
			productivity/tryton/product

.include <bsd.port.mk>
