# $OpenBSD: Makefile,v 1.6 2013/03/11 11:42:45 espie Exp $

COMMENT=	figure out when to fetch RSS Feeds

MODULES=	cpan
DISTNAME=	XML-RSS-Timing-1.07
REVISION=	1
CATEGORIES=	textproc
USE_GROFF =	Yes

# GPL
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
