# $OpenBSD: Makefile,v 1.22 2014/11/10 19:10:47 benoit Exp $

SHARED_ONLY=	Yes

COMMENT=	interface to the system's process table

DISTNAME =	Proc-ProcessTable-0.51
CATEGORIES=	sysutils

# Artistic License
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB += c kvm

MODULES=	cpan

.include <bsd.port.mk>
