# $OpenBSD: Makefile,v 1.13 2014/04/13 01:01:39 naddy Exp $

COMMENT=	implement a back-propagation feed-forward neural network

MODULES=	cpan
DISTNAME=	AI-NeuralNet-BackProp-0.89
REVISION=	3
CATEGORIES=	math

# Perl
PERMIT_PACKAGE_CDROM=	Yes

EXTRACT_SUFX=	.zip

WRKDIST=	${WRKDIR}

.include <bsd.port.mk>
