# $OpenBSD: Makefile,v 1.5 2016/03/20 19:56:38 naddy Exp $

COMMENT =		checks to see if the module can be loaded

MODULES =		cpan
PKG_ARCH =		*
DISTNAME =		Test-Requires-0.10
CATEGORIES =		devel

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
