# $OpenBSD: Makefile,v 1.15 2013/10/11 23:48:13 naddy Exp $

COMMENT=	module to encode and decode objects

DISTNAME=	Convert-BER-1.32
REVISION=	0
EPOCH=		0
CATEGORIES=	converters
MODULES=	cpan

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
