# $OpenBSD: Makefile,v 1.2 2013/03/11 10:50:18 espie Exp $

COMMENT =	capture STDOUT and STDERR from Perl code, subprocesses or XS

MODULES =	cpan
DISTNAME =	IO-CaptureOutput-1.1102
REVISION =	0
CATEGORIES =	devel

# Perl
PERMIT_PACKAGE_CDROM=   Yes

.include <bsd.port.mk>
