# $OpenBSD: Makefile,v 1.5 2016/03/20 19:56:25 naddy Exp $

COMMENT =	capture STDOUT and STDERR from Perl code, subprocesses or XS

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	IO-CaptureOutput-1.1104
CATEGORIES =	devel

# Perl
PERMIT_PACKAGE_CDROM=   Yes

.include <bsd.port.mk>
