# $OpenBSD: Makefile,v 1.7 2013/03/11 11:41:27 espie Exp $

COMMENT=	HTTP authentication

V=		2.1.8
DISTNAME=	Auth_HTTP-${V}
PKGNAME=	pear-Auth-HTTP-${V}
CATEGORIES=	security

MODULES=	www/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
