# $OpenBSD: Makefile,v 1.4 2013/12/06 12:00:16 jasper Exp $

COMMENT=	RSpec tests for Puppet manifests
DISTNAME=	rspec-puppet-1.0.1
REVISION=	0

HOMEPAGE=	http://rspec-puppet.com/

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	devel/ruby-rspec/rspec,${MODRUBY_FLAVOR}

.include <bsd.port.mk>
