# $OpenBSD: Makefile,v 1.11 2013/10/11 23:50:48 naddy Exp $

COMMENT=	implementation of the RC4 encryption algorithm

MODULES=	cpan
DISTNAME=	Crypt-RC4-2.02
REVISION=	2
CATEGORIES=	security

# Perl
PERMIT_PACKAGE_CDROM=   Yes

.include <bsd.port.mk>	
