# $OpenBSD: Makefile,v 1.12 2013/10/11 23:48:35 naddy Exp $

COMMENT=	load modules and create objects on demand

MODULES=	cpan
DISTNAME=	Class-Loader-2.03
REVISION=	1
CATEGORIES=	devel

PERMIT_PACKAGE_CDROM=   Yes

.include <bsd.port.mk>
