# $OpenBSD: Makefile,v 1.8 2012/01/28 11:20:52 espie Exp $

COMMENT =	thumbnail for profile avatars

DISTNAME = 	imagecache_profiles-6.x-1.3
PKGNAME =	drupal6-imagecache-profiles-1.3
REVISION =	1
RUN_DEPENDS =	www/drupal6/imagecache

.include <bsd.port.mk>
