# $OpenBSD: Makefile,v 1.8 2013/03/11 11:35:54 espie Exp $

COMMENT=	perl module to get FQDN

MODULES=	cpan
DISTNAME=	Sys-Hostname-Long-1.4
REVISION=	2
CATEGORIES=	net
USE_GROFF =	Yes

# GPL
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
