# $OpenBSD: Makefile,v 1.19 2016/03/20 19:56:13 naddy Exp $

COMMENT =		stat() with BSD 4.4 extentions

DISTNAME =		BSD-stat-1.35
REVISION =		2

CATEGORIES =		devel

# perl
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB +=		c perl

MODULES =		cpan

.include <bsd.port.mk>
