# $OpenBSD: Makefile,v 1.9 2016/03/20 19:56:16 naddy Exp $

COMMENT=	Abstract class wrapper for Autoloader

MODULES=	cpan
PKG_ARCH=	*
DISTNAME=	Class-MethodMapper-1.0
REVISION=	2
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
