# $OpenBSD: Makefile,v 1.8 2013/10/11 23:50:27 naddy Exp $

COMMENT=	Perl Simple Network Pager Protocol Client

MODULES=	cpan
DISTNAME=	Net-SNPP-1.17
REVISION=	2
CATEGORIES=	net devel

# perl artistic license
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
