# $OpenBSD: Makefile,v 1.11 2014/02/08 19:48:22 espie Exp $

COMMENT =	image cck field

DISTNAME = 	imagefield-6.x-3.11
PKGNAME =	drupal6-imagefield-3.11
REVISION =	0

RUN_DEPENDS =	www/drupal6/filefield

.include <bsd.port.mk>
