# $OpenBSD: Makefile,v 1.42 2015/10/13 06:30:47 bentley Exp $

COMMENT =	creating & editing GIF images and animations

DISTNAME =	gifsicle-1.88
CATEGORIES =	graphics

# GPLv2
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB =		c ICE SM X11 m

HOMEPAGE =	http://www.lcdf.org/gifsicle/

MASTER_SITES =	http://www.lcdf.org/gifsicle/

CONFIGURE_STYLE =	gnu
SEPARATE_BUILD =	Yes

.include <bsd.port.mk>
