# $OpenBSD: Makefile,v 1.5 2015/03/15 08:52:14 ajacoutot Exp $

MODPY_EGG_VERSION =	3.2.2

TRYTOND_MODULE =	project_invoice
REVISION =		0

RUN_DEPENDS =		productivity/tryton/project \
			productivity/tryton/project_revenue \
			productivity/tryton/timesheet \
			productivity/tryton/account_invoice \
			productivity/tryton/product

.include <bsd.port.mk>
