# $OpenBSD: Makefile,v 1.11 2013/03/11 11:42:45 espie Exp $

COMMENT=	access/create XML files/datas easily

MODULES=	cpan
DISTNAME=	XML-Smart-1.76
REVISION=	0
CATEGORIES=	textproc

# GPL/Artistic
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=		textproc/p5-Object-MultiType

TEST_DEPENDS=	devel/p5-Test-Pod

.include <bsd.port.mk>
