# $OpenBSD: Makefile,v 1.7 2013/10/11 23:50:20 naddy Exp $

COMMENT=	lightweight SOCKS 4 and SOCKS 5 proxy
DISTNAME=	nylon-1.21
REVISION=	0
CATEGORIES=	net

HOMEPAGE=	http://monkey.org/~marius/nylon/

# BSD
PERMIT_PACKAGE_CDROM=	Yes
WANTLIB=		c event

MASTER_SITES=	${HOMEPAGE}

CONFIGURE_STYLE=gnu

.include <bsd.port.mk> 
