# $OpenBSD: Makefile,v 1.21 2013/10/11 23:50:17 naddy Exp $

COMMENT=	HTTP tunneling utility

DISTNAME=	httptunnel-3.3
REVISION=	0
CATEGORIES=	net

MASTER_SITES=	${MASTER_SITE_GNU:=httptunnel/}

HOMEPAGE=	http://www.nocrew.org/software/httptunnel/

PERMIT_PACKAGE_CDROM=	Yes
WANTLIB=		c

SEPARATE_BUILD=	Yes
CONFIGURE_STYLE= gnu

.include <bsd.port.mk>
