# $OpenBSD: Makefile,v 1.2 2016/03/20 19:57:10 naddy Exp $

COMMENT =	module for reflowing text files

MODULES =	cpan
DISTNAME =	Text-Reflow-1.09
CATEGORIES =	textproc

# perl
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB =	perl

.include <bsd.port.mk>
