# $OpenBSD: Makefile,v 1.12 2013/10/11 23:49:27 naddy Exp $

COMMENT=	calling UNIVERSAL::isa as a function

MODULES=	cpan
DISTNAME=	UNIVERSAL-isa-1.03
PKGNAME=	p5-Universal-isa-1.03
REVISION=	1
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

CONFIGURE_STYLE=modbuild

.include <bsd.port.mk>
