# $OpenBSD: Makefile,v 1.4 2016/03/20 19:56:34 naddy Exp $

COMMENT =	module for when strings are too long to be displayed in

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	String-Truncate-1.100602
CATEGORIES =	devel

# Perl
PERMIT_PACKAGE_CDROM =	Yes

RUN_DEPENDS =	devel/p5-Sub-Exporter

.include <bsd.port.mk>
