# $OpenBSD: Makefile,v 1.1.1.1 2014/03/16 21:42:47 afresh1 Exp $

COMMENT =	convert English text to numbers
DISTNAME =	Lingua-EN-Words2Nums-0.18
REVISION =	0
CATEGORIES =	textproc

# same terms as Perl itself
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

.include <bsd.port.mk>
