# $OpenBSD: Makefile,v 1.7 2013/03/11 11:42:45 espie Exp $

COMMENT=	module for DOCTYPE based XML output

MODULES=	cpan
DISTNAME=	XML-AutoWriter-0.39
REVISION=	1
CATEGORIES=	textproc
USE_GROFF =	Yes

# BSD
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
