# $OpenBSD: Makefile,v 1.8 2013/03/11 10:50:17 espie Exp $

COMMENT=	determine file type using magic

MODULES=	cpan
DISTNAME=	File-Type-0.22
REVISION=	2
CATEGORIES=	devel
USE_GROFF =	Yes

# Artistic
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
