# $OpenBSD: Makefile,v 1.4 2012/01/28 11:20:52 espie Exp $

COMMENT =	custom teaser and body fields using templates

DISTNAME = 	contemplate-6.x-1.2
PKGNAME =	drupal6-contemplate-1.2
REVISION =	0

.include <bsd.port.mk>
