# $OpenBSD: Makefile,v 1.10 2014/05/10 03:02:08 afresh1 Exp $

COMMENT =	helper for installing code into packages

DISTNAME =	Sub-Install-0.927
REVISION =	0
CATEGORIES =	devel

# perl_5
PERMIT_PACKAGE_CDROM =	Yes

MODULES =	cpan

TEST_DEPENDS =	devel/p5-Test-Output 

.include <bsd.port.mk>
