# $OpenBSD: Makefile,v 1.10 2014/06/14 23:26:00 sthen Exp $

SHARED_ONLY=	Yes

COMMENT= 	interface to the Serpent encryption algorithm

MODULES=	cpan
DISTNAME=	Crypt-Serpent-1.01
REVISION=	5
CATEGORIES=	security

# perl
PERMIT_PACKAGE_CDROM=   Yes

WANTLIB += c

.include <bsd.port.mk>
