# $OpenBSD: Makefile,v 1.16 2015/07/19 10:52:33 zhuk Exp $

COMMENT=	extensions to Class::DBI for MySQL

MODULES=	cpan databases/mariadb
DISTNAME=	Class-DBI-mysql-1.00
REVISION=	3
CATEGORIES=	databases

# Same as Perl
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	databases/p5-Class-DBI \
		databases/p5-DBD-mysql

.include <bsd.port.mk>
