# $OpenBSD: Makefile,v 1.4 2013/03/11 11:35:47 espie Exp $

COMMENT =		Haskell package for determining the hostname

DISTNAME =		hostname-1.0
REVISION =		2
CATEGORIES =		devel net

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

.include <bsd.port.mk>
