# $OpenBSD: Makefile,v 1.19 2016/03/20 19:56:07 naddy Exp $

COMMENT=	interface to the uulib library

DISTNAME =	Convert-UUlib-1.4
EPOCH =		1
CATEGORIES=	converters
MODULES=	cpan
REVISION =	2

# Perl
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB += c perl

.include <bsd.port.mk>
