# $OpenBSD: Makefile,v 1.10 2016/03/20 19:56:36 naddy Exp $

COMMENT =	perl module for portable testing of commands and scripts

DISTNAME =	Test-Cmd-1.09
CATEGORIES =	devel

# perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan
PKG_ARCH =		*

.include <bsd.port.mk>
