# $OpenBSD: Makefile,v 1.7 2015/01/08 07:42:03 benoit Exp $

COMMENT=	perl module for portable testing of commands and scripts

DISTNAME =	Test-Cmd-1.07
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

MODULES=cpan

.include <bsd.port.mk>
