# $OpenBSD: Makefile,v 1.2 2013/03/11 11:35:53 espie Exp $

COMMENT =	IP fragment reassembly for Net::Pcap

DISTNAME =	Net-Pcap-Reassemble-0.05
REVISION =	0
CATEGORIES =	net
MODULES =	cpan

# Perl
PERMIT_PACKAGE_CDROM =	Yes

RUN_DEPENDS = net/p5-Net-Pcap

.include <bsd.port.mk>
