# $OpenBSD: Makefile,v 1.5 2013/10/11 23:50:06 naddy Exp $

COMMENT=	Fibonacci numbers

DISTNAME=	Math-Fibonacci-1.5
REVISION=	1
CATEGORIES=	math

# Perl
PERMIT_PACKAGE_CDROM=	Yes

MODULES=	cpan

.include <bsd.port.mk>
