# $OpenBSD: Makefile,v 1.5 2013/03/11 11:41:33 espie Exp $
#

COMMENT =		execute jobs in parallel

DISTNAME =		xjobs-20100915
REVISION =		0

CATEGORIES =		sysutils

HOMEPAGE =		http://www.maier-komor.de/xjobs.html

# License GPLv2
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB =		c m

MASTER_SITES =		http://www.maier-komor.de/xjobs/
EXTRACT_SUFX =		.tgz

CONFIGURE_STYLE =	gnu
USE_GROFF =		Yes

NO_TEST =		Yes

.include <bsd.port.mk>
