# $OpenBSD: Makefile,v 1.9 2013/04/02 14:41:05 espie Exp $

COMMENT =	import CSV users to drupal

DISTNAME = 	user_import-6.x-4.2
PKGNAME =	drupal6-user-import-4.2
REVISION =	0

.include <bsd.port.mk>
