#!/bin/sh
#
# $OpenBSD$

if [ ! -f /etc/mailer.conf.pre-sendmail ]; then
    echo "can't find /etc/mailer.conf.pre-sendmail, sendmail not disabled" >&2
    exit 1
fi

if [ -f /etc/mailer.conf ]; then
    mv -f /etc/mailer.conf /etc/mailer.conf.sendmail
    mv -f /etc/mailer.conf.pre-sendmail /etc/mailer.conf
    echo "sendmail mailer.conf disabled, old mailer.conf enabled" >&1
else
    echo "can't find /etc/mailer.conf, sendmail not disabled" >&1
    exit 1
fi
