# $OpenBSD: Makefile,v 1.5 2013/10/11 23:48:40 naddy Exp $

COMMENT=        hexadecimal dumper

MODULES=	cpan
DISTNAME=	Data-HexDump-0.02
REVISION=	1
CATEGORIES=     devel

# perl
PERMIT_PACKAGE_CDROM=   Yes

.include <bsd.port.mk>
