# $OpenBSD: Makefile,v 1.18 2013/03/11 11:23:57 espie Exp $

BROKEN= 	needs work on bitrig

COMMENT=	Garmin GPS upload/download utilities

DISTNAME=	garmin-utils-2.4
REVISION=	2
CATEGORIES=	misc geo
MASTER_SITES=	ftp://ftp.snafu.org/pub/

PERMIT_PACKAGE_CDROM=	Yes

WANTLIB=		c

.include <bsd.port.mk>
