# $OpenBSD: Makefile,v 1.6 2013/10/11 23:49:05 naddy Exp $

COMMENT =		Write a demo program from a tutorial POD

MODULES =		cpan
DISTNAME =		Pod-ToDemo-1.01
REVISION =		1
CATEGORIES =		devel
CPAN_AUTHOR =		CHROMATIC

# Perl
PERMIT_PACKAGE_CDROM =	Yes

TEST_DEPENDS =	devel/p5-Test-Exception

.include <bsd.port.mk>
