# $OpenBSD: Makefile,v 1.21 2016/03/20 19:56:08 naddy Exp $

COMMENT =	tie class for a simple ASCII database
DISTNAME =	AsciiDB-TagFile-1.06
REVISION =	2
CATEGORIES =	databases
MODULES =	cpan
PKG_ARCH =	*

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
