# $OpenBSD: Makefile,v 1.5 2013/10/11 23:50:26 naddy Exp $

COMMENT=	Perl interface to the PH protocol

DISTNAME=	Net-PH-2.21
REVISION=	1
CATEGORIES=	net
MODULES=	cpan

# Perl License
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
