# $OpenBSD: Makefile,v 1.6 2016/03/20 19:56:54 naddy Exp $

COMMENT=	Perl interface to the PH protocol

DISTNAME=	Net-PH-2.21
REVISION=	1
CATEGORIES=	net
MODULES=	cpan
PKG_ARCH=	*

# Perl License
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
