# $OpenBSD: Makefile,v 1.4 2015/03/15 13:21:47 ajacoutot Exp $

MODPY_EGG_VERSION =	3.2.3

TRYTOND_MODULE =	party_relationship
REVISION =		0

RUN_DEPENDS =		productivity/tryton/party

.include <bsd.port.mk>
