# $OpenBSD: Makefile,v 1.5 2015/09/19 21:33:53 ajacoutot Exp $

MODPY_EGG_VERSION =	3.2.4

TRYTOND_MODULE =	party_relationship
REVISION =		0

RUN_DEPENDS =		productivity/tryton/party

.include <bsd.port.mk>
