# $OpenBSD: Makefile,v 1.3 2015/01/16 09:59:20 ajacoutot Exp $

MODPY_EGG_VERSION =	3.2.2

TRYTOND_MODULE =	party_relationship
REVISION =		0

RUN_DEPENDS =		productivity/tryton/party

.include <bsd.port.mk>
