# $OpenBSD: Makefile,v 1.13 2014/04/29 08:05:31 ajacoutot Exp $

TRYTOND_MODULE =	account
REVISION =		0

RUN_DEPENDS =		productivity/tryton/company \
			productivity/tryton/currency \
			productivity/tryton/party

.include <bsd.port.mk>
