# $OpenBSD: Makefile,v 1.14 2013/10/11 23:50:08 naddy Exp $

COMMENT=	manage sets of integers

MODULES=	cpan
DISTNAME=	Set-IntSpan-1.13
REVISION=	1
CATEGORIES=	math

PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
