# $OpenBSD: Makefile,v 1.16 2013/03/11 11:44:47 espie Exp $

COMMENT=	package provides methods for HTML forms

DISTNAME=	HTML_QuickForm-3.2.13
REVISION=	0
CATEGORIES=	devel www

MODULES=	www/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	www/pear-HTML-Common2>=0.1.0

.include <bsd.port.mk>
