# $OpenBSD: Makefile,v 1.15 2014/01/01 20:46:29 naddy Exp $

COMMENT =	typing break alarm and timer

DISTNAME =	xwrits-2.26
REVISION =	0
CATEGORIES =	x11
HOMEPAGE =	http://www.lcdf.org/~eddietwo/xwrits/

# GPLv2
PERMIT_PACKAGE_CDROM =		Yes

WANTLIB =		ICE SM X11 Xext Xinerama c m 

MASTER_SITES =		${HOMEPAGE}

SEPARATE_BUILD =	Yes
CONFIGURE_STYLE =	gnu

NO_TEST = 		Yes

.include <bsd.port.mk>
