# $OpenBSD: Makefile,v 1.1.1.1 2014/07/13 08:58:35 pascal Exp $

COMMENT =	programming language designed for orang-utans

MODULES =	cpan
DISTNAME =	Language-Ook-1.0.2
REVISION =	0
CATEGORIES =	lang

HOMEPAGE =	http://www.dangermouse.net/esoteric/ook.html

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
