# $OpenBSD: Makefile,v 1.5 2014/06/14 23:25:41 sthen Exp $

SHARED_ONLY =		yes

COMMENT =		efficient generation of combinatorial sequences

DISTNAME =		Algorithm-Combinatorics-0.27
REVISION =		2
CATEGORIES =		math

CPAN_AUTHOR =		FXN

# Perl
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB += c

MODULES =		cpan

MAKE_ENV=		TEST_POD=Yes

.include <bsd.port.mk>
