# $OpenBSD: Makefile,v 1.5 2013/03/11 11:23:52 espie Exp $

COMMENT = 	IMAP client interface with lots of features

MODULES =	cpan
DISTNAME =	Mail-IMAPTalk-1.03
REVISION =	2
CATEGORIES =	mail
USE_GROFF =	Yes

# Perl
PERMIT_PACKAGE_CDROM =		Yes

.include <bsd.port.mk>
