# $OpenBSD: Makefile,v 1.14 2013/03/11 11:44:45 espie Exp $

COMMENT=	HTML output stream class

MODULES=	cpan
DISTNAME=	HTML-Stream-1.60
REVISION=	1
CATEGORIES=	www devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=   Yes

.include <bsd.port.mk>
