# $OpenBSD: Makefile,v 1.2 2016/03/20 19:56:33 naddy Exp $

COMMENT =		call isa, can, does and DOES safely

MODULES =		cpan
PKG_ARCH =		*
DISTNAME =		Safe-Isa-1.000005
CATEGORIES =		devel

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
