# $OpenBSD: Makefile,v 1.8 2013/10/11 23:49:08 naddy Exp $

COMMENT=	module for shell-like regular expressions

MODULES=	cpan
DISTNAME=	Regexp-Shellish-0.93
REVISION=	2
CATEGORIES=	devel

PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
