# $OpenBSD: Makefile,v 1.1.1.1 2013/07/18 21:01:06 kili Exp $

COMMENT =		Haskell 98 natural numbers

DISTNAME =		nats-0.1
REVISION =		0
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

.include <bsd.port.mk>
