# $OpenBSD: Makefile,v 1.20 2014/07/12 23:54:32 jasper Exp $

SHARED_ONLY=	Yes

COMMENT=	generalisation of wantarray

MODULES=	cpan
DISTNAME=	Want-0.23
REVISION=	0
CATEGORIES=	devel

# Artistic
PERMIT_PACKAGE_CDROM=	Yes

CPAN_AUTHOR=	ROBIN

.include <bsd.port.mk>
