# $OpenBSD: Makefile,v 1.13 2013/03/11 11:35:47 espie Exp $

COMMENT=	small network calculator

DISTNAME=	ipcalc-1.4
REVISION=	0
CATEGORIES=	net

HOMEPAGE=	https://github.com/pyr/ipcalc

# BSD
PERMIT_PACKAGE_CDROM=	Yes

MASTER_SITES=	https://github.com/downloads/pyr/ipcalc/

FAKE_FLAGS=	MANDIR="${PREFIX}/man/man"

NO_TEST=	Yes
WANTLIB=	c

.include <bsd.port.mk>
