COMMENT=	System Compiler Meta Package

PKGNAME=	syscomp-1.0
RELEASE=	0

MAINTAINER=	Marco Peereboom <marco@bitrig.com>

RUN_DEPENDS=	devel/git		\
		devel/binutils-bitrig	\
		devel/llvm

.include <bsd.port.mk>
