# $OpenBSD: Makefile,v 1.19 2014/06/14 23:26:01 sthen Exp $

SHARED_ONLY=	Yes

COMMENT=	interface to md5 message-digest algorithm

MODULES=	cpan
DISTNAME=	MD5-1.7
REVISION=	5
CATEGORIES=	security

# Perl
PERMIT_PACKAGE_CDROM=   Yes

WANTLIB += c

.include <bsd.port.mk>
