# $OpenBSD: Makefile,v 1.14 2013/12/18 12:31:58 sthen Exp $

COMMENT=	interface to HMAC Message-Digest Algorithms

MODULES=	cpan
DISTNAME=	Digest-HMAC-1.03
REVISION=	0
CATEGORIES=	security

# Perl
PERMIT_PACKAGE_CDROM=   Yes

.include <bsd.port.mk>	
